removed B since it is on by default when reading from stdin. turned on -p to preserve permissions

diff --git a/shell_scripts/tarcp b/shell_scripts/tarcp
--- a/shell_scripts/tarcp
+++ b/shell_scripts/tarcp
@@ -2,9 +2,16 @@
 #
 # tarcp indir outdir
 #
-# copy the input directory into the output directory.
+# copy the input directory into the output directory, not over-writing existing
+# files if they are newer or the same age.
+#
+# Note reblocking is turned on automatically since we are reading from stdin
+#
 # the output directory is created if it does not exist.
 #
+
+# exit when any command fails
+set -e
 
 if [[ $# -lt 2 ]]; then
     echo "tarcp indir outdir"
@@ -13,6 +20,12 @@ fi
 
 indir=$1
 outdir=$2
+
+if [[ ! -e $indir ]]; then
+    echo "input directory does not exist: $indir"
+    exit 1
+fi
+
 if [[ ! -e $outdir ]]; then
     echo "making output directory: $outdir"
     mkdir -p "$outdir"
@@ -21,4 +34,4 @@ fi
 outdir_abs=$(readlink -m $outdir)
 
 cd "$indir"
-tar cf - . | (cd "$outdir_abs" && tar --keep-newer-files -x -v -f -)
+tar cf - . | (cd "$outdir_abs" && tar --keep-newer-files -xvpf -)
